In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset_transaksi = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/transaksi_dqlab_retail.tsv', sep='\t')

dataset_transaksi

      Kode Transaksi              Nama Barang
0                 #1                     Kaos
1                 #1             Shampo Biasa
2                 #1      Sepatu Sport merk Z
3                 #1            Serum Vitamin
4                 #1  Baju Renang Pria Dewasa
...              ...                      ...
33663          #3450     Flat Shoes Ballerina
33664          #3450       Sepatu Sandal Anak
33665          #3450      Sepatu Kulit Casual
33666          #3450     Celana Jogger Casual
33667          #3450      Sepatu Sport merk Z

[33668 rows x 2 columns]

In [3]:
dataset_transaksi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33668 entries, 0 to 33667
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Kode Transaksi  33668 non-null  object
 1   Nama Barang     33668 non-null  object
dtypes: object(2)
memory usage: 526.2+ KB

In [4]:
#Flag digunakan untuk menandakan barang/item terdapat pada basket.
dataset_transaksi['Flag'] = 1

dataset_transaksi

      Kode Transaksi              Nama Barang  Flag
0                 #1                     Kaos     1
1                 #1             Shampo Biasa     1
2                 #1      Sepatu Sport merk Z     1
3                 #1            Serum Vitamin     1
4                 #1  Baju Renang Pria Dewasa     1
...              ...                      ...   ...
33663          #3450     Flat Shoes Ballerina     1
33664          #3450       Sepatu Sandal Anak     1
33665          #3450      Sepatu Kulit Casual     1
33666          #3450     Celana Jogger Casual     1
33667          #3450      Sepatu Sport merk Z     1

[33668 rows x 3 columns]

In [5]:
#Melakukan pengelompokkan Flag berdasarkan kolom Kode Transaksi dan Nama Barang
basket = dataset_transaksi.groupby(['Kode Transaksi','Nama Barang'])['Flag'].sum().unstack().reset_index().fillna(0).set_index('Kode Transaksi')

basket

Nama Barang,Atasan Baju Belang,Atasan Kaos Putih,Baju Batik Wanita,Baju Kaos Anak - Karakter Kartun,Baju Kaos Anak - Superheroes,Baju Kaos Olahraga,Baju Kemeja Putih,Baju Renang Anak Perempuan,Baju Renang Pria Anak-anak,Baju Renang Pria Dewasa,...,Tas Multifungsi,Tas Pinggang Wanita,Tas Ransel Mini,Tas Sekolah Anak Laki-laki,Tas Sekolah Anak Perempuan,Tas Tangan,Tas Travel,Tas Waist Bag,Wedges Hitam,Woman Ripped Jeans
Kode Transaksi,,,,,,,,,,,,,,,,,,,,,
#1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#10,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
#100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#1000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#1001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
#995,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
#996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
#997,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#998,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
#999,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [7]:
#Membuat function untuk menormalisasi data
def encode_units(x):
	if x <= 0 :
		return 0
	if x > 0:
		return 1

#Menerapkan fungsi encode_units pada dataset	
basket_encode = basket.applymap(encode_units)

#Menampilkan basket_encode
basket_encode

Nama Barang,Atasan Baju Belang,Atasan Kaos Putih,Baju Batik Wanita,Baju Kaos Anak - Karakter Kartun,Baju Kaos Anak - Superheroes,Baju Kaos Olahraga,Baju Kemeja Putih,Baju Renang Anak Perempuan,Baju Renang Pria Anak-anak,Baju Renang Pria Dewasa,...,Tas Multifungsi,Tas Pinggang Wanita,Tas Ransel Mini,Tas Sekolah Anak Laki-laki,Tas Sekolah Anak Perempuan,Tas Tangan,Tas Travel,Tas Waist Bag,Wedges Hitam,Woman Ripped Jeans
Kode Transaksi,,,,,,,,,,,,,,,,,,,,,
#1,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
#10,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
#100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
#1000,0,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
#1001,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
#995,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0
#996,0,0,0,0,0,0,0,0,0,1,...,1,0,0,1,0,0,1,0,0,0
#997,0,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
#998,0,0,1,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
#999,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [8]:
basket_encode = basket_encode.astype('bool')

In [9]:
#Mengimport algoritma apriori
from mlxtend.frequent_patterns import apriori

#Menerapkan algoritma apriori untuk mendapatkan frequent_itemset
frequent_itemset = apriori(basket_encode, min_support=0.03, use_colnames=True)

frequent_itemset

       support                                           itemsets
0     0.118841                                (Atasan Kaos Putih)
1     0.380290                                (Baju Batik Wanita)
2     0.121159                 (Baju Kaos Anak - Karakter Kartun)
3     0.115942                     (Baju Kaos Anak - Superheroes)
4     0.089275                               (Baju Kaos Olahraga)
...        ...                                                ...
1255  0.031304  (Cover Koper, Baju Kaos Anak - Karakter Kartun...
1256  0.042609  (Serum Vitamin, Baju Kaos Anak - Superheroes, ...
1257  0.038551  (Baju Renang Pria Dewasa, Wedges Hitam, Tas Tr...
1258  0.047536  (Serum Vitamin, Shampo Biasa, Sepatu Sekolah H...
1259  0.037391  (Baju Renang Pria Dewasa, Wedges Hitam, Tas Tr...

[1260 rows x 2 columns]

In [10]:
#Mengimport association_rules
from mlxtend.frequent_patterns import association_rules

#Menerapkan association_rules berdasarkan frequent_itemset
rules = association_rules(frequent_itemset, metric='lift', min_threshold=1).sort_values('lift', ascending=False).reset_index(drop=True)

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,"(Cover Koper, Tas Tangan)","(Tank Top, Baju Kaos Anak - Karakter Kartun, C...",0.031884,0.034493,0.031304,0.981818,28.464477,0.030205,53.102899,0.996646
1,"(Tank Top, Baju Kaos Anak - Karakter Kartun, C...","(Cover Koper, Tas Tangan)",0.034493,0.031884,0.031304,0.907563,28.464477,0.030205,10.473254,0.999338
2,"(Cover Koper, Baju Kaos Anak - Karakter Kartun...","(Tank Top, Tas Tangan)",0.034203,0.032464,0.031304,0.915254,28.193099,0.030194,11.416928,0.998688
3,"(Tank Top, Tas Tangan)","(Cover Koper, Baju Kaos Anak - Karakter Kartun...",0.032464,0.034203,0.031304,0.964286,28.193099,0.030194,27.042319,0.996893
4,"(Tas Tangan, Celana Pendek Jeans)","(Cover Koper, Baju Kaos Anak - Karakter Kartun...",0.032464,0.035072,0.031304,0.964286,27.494097,0.030166,27.017971,0.995961
...,...,...,...,...,...,...,...,...,...,...
5143,(Tali Pinggang Anak),(Wedges Hitam),0.150725,0.246087,0.037101,0.246154,1.000272,0.000010,1.000089,0.000320
5144,"(Serum Vitamin, Tas Waist Bag)",(Baju Kemeja Putih),0.129855,0.363768,0.047246,0.363839,1.000196,0.000009,1.000112,0.000225
5145,(Baju Kemeja Putih),"(Serum Vitamin, Tas Waist Bag)",0.363768,0.129855,0.047246,0.129880,1.000196,0.000009,1.000029,0.000307
5146,"(Serum Vitamin, Hair Dryer)",(Tali Pinggang Gesper Pria),0.122609,0.290725,0.035652,0.290780,1.000191,0.000007,1.000078,0.000218
5147,(Tali Pinggang Gesper Pria),"(Serum Vitamin, Hair Dryer)",0.290725,0.122609,0.035652,0.122632,1.000191,0.000007,1.000027,0.000269